[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_solana_app = "9EEKqW83vxEStkjVQ44f9gMKyviySsxKFH8APC2XVVSg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
